In [1]:
import sqlite3
import pandas as pd

db_path = "/Users/saigonfury/Projects/Cadence_Focus/data/database/cf.db"

with sqlite3.connect(db_path) as conn:
    df = pd.read_sql_query(
        "SELECT * FROM financial_facts WHERE COMPANY =",
        conn,
    )

df

,fact_id,company_number,document_id,concept,concept_local_name,value_raw,value_numeric,unit,context_ref,source_url
0,1,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Creditors,Creditors,"6,166",6166,GBP,CreditorsHypercube_cfwd_31_03_2019_Set1,https://document-api.company-information.servi...
1,2,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:AverageNumberEmployeesDuringPeriod,AverageNumberEmployeesDuringPeriod,0,0,pure,FY_31_03_2020,https://document-api.company-information.servi...
2,3,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:AverageNumberEmployeesDuringPeriod,AverageNumberEmployeesDuringPeriod,0,0,pure,FY_31_03_2019,https://document-api.company-information.servi...
3,4,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:PropertyPlantEquipment,PropertyPlantEquipment,20,20,GBP,cfwd_31_03_2020,https://document-api.company-information.servi...
4,5,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:PropertyPlantEquipment,PropertyPlantEquipment,30,30,GBP,cfwd_31_03_2019,https://document-api.company-information.servi...
5,6,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Debtors,Debtors,93,93,GBP,cfwd_31_03_2020,https://document-api.company-information.servi...
6,7,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Debtors,Debtors,169,169,GBP,cfwd_31_03_2019,https://document-api.company-information.servi...
7,8,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:CashBankOnHand,CashBankOnHand,"1,150",1150,GBP,cfwd_31_03_2020,https://document-api.company-information.servi...
8,9,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:CashBankOnHand,CashBankOnHand,"2,083",2083,GBP,cfwd_31_03_2019,https://document-api.company-information.servi...
9,10,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:CurrentAssets,CurrentAssets,"1,243",1243,GBP,cfwd_31_03_2020,https://document-api.company-information.servi...
10,11,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:CurrentAssets,CurrentAssets,"2,252",2252,GBP,cfwd_31_03_2019,https://document-api.company-information.servi...
11,12,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Creditors,Creditors,"7,923",7923,GBP,CreditorsHypercube_cfwd_31_03_2020_Set1,https://document-api.company-information.servi...
12,14,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:NetCurrentAssetsLiabilities,NetCurrentAssetsLiabilities,"6,680",-6680,GBP,cfwd_31_03_2020,https://document-api.company-information.servi...
13,15,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:NetCurrentAssetsLiabilities,NetCurrentAssetsLiabilities,"3,914",-3914,GBP,cfwd_31_03_2019,https://document-api.company-information.servi...
14,16,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:TotalAssetsLessCurrentLiabilities,TotalAssetsLessCurrentLiabilities,"6,660",-6660,GBP,cfwd_31_03_2020,https://document-api.company-information.servi...
15,17,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:TotalAssetsLessCurrentLiabilities,TotalAssetsLessCurrentLiabilities,"3,884",-3884,GBP,cfwd_31_03_2019,https://document-api.company-information.servi...
16,18,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Equity,Equity,103,103,GBP,EquitySOCI-SegmentsHypercube_cfwd_31_03_2020_Set2,https://document-api.company-information.servi...
17,19,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Equity,Equity,103,103,GBP,EquitySOCIHypercube_cfwd_31_03_2019_Set2,https://document-api.company-information.servi...
18,20,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Equity,Equity,"6,763",-6763,GBP,EquitySOCI-SegmentsHypercube_cfwd_31_03_2020_Set3,https://document-api.company-information.servi...
19,21,05150526,vBRLLhySgOGunl2dfkHTRblkVonL6vmNfBsfSHlmIu4,ns6:Equity,Equity,"3,987",-3987,GBP,EquitySOCIHypercube_cfwd_31_03_2019_Set3,https://document-api.company-information.servi...

In [4]:
with sqlite3.connect(db_path) as conn:
    df = pd.read_sql_query(
        '''
        SELECT
            c.company_name,
            f.company_number,
            f.concept_local_name,
            f.value_numeric,
            f.unit,
            f.context_ref
        FROM financial_facts AS f
        LEFT JOIN company AS c
            ON f.company_number = c.company_number;
        ''',
        conn,
    )

df

,company_name,company_number,concept_local_name,value_numeric,unit,context_ref
0,SCCI LIMITED,05150526,Creditors,6166.0,GBP,CreditorsHypercube_cfwd_31_03_2019_Set1
1,SCCI LIMITED,05150526,AverageNumberEmployeesDuringPeriod,0.0,pure,FY_31_03_2020
2,SCCI LIMITED,05150526,AverageNumberEmployeesDuringPeriod,0.0,pure,FY_31_03_2019
3,SCCI LIMITED,05150526,PropertyPlantEquipment,20.0,GBP,cfwd_31_03_2020
4,SCCI LIMITED,05150526,PropertyPlantEquipment,30.0,GBP,cfwd_31_03_2019
...,...,...,...,...,...,...
75,CADENCE EQUITY PARTNERS LIMITED,10238359,OtherCreditors,66.0,GBP,E_B_M
76,CADENCE EQUITY PARTNERS LIMITED,10238359,AccruedLiabilitiesDeferredIncome,93988.0,GBP,B_B_M
77,CADENCE EQUITY PARTNERS LIMITED,10238359,AccruedLiabilitiesDeferredIncome,190393.0,GBP,E_B_M
78,CADENCE EQUITY PARTNERS LIMITED,10238359,Creditors,214372.0,GBP,B_B_M
79,CADENCE EQUITY PARTNERS LIMITED,10238359,Creditors,389665.0,GBP,E_B_M

In [11]:
with sqlite3.connect(db_path) as conn:
    columns = pd.read_sql_query(
        "PRAGMA table_info(financial_facts)",
        conn,
    )

columns[["name", "type"]]

with sqlite3.connect(db_path) as conn:
    df = pd.read_sql_query(
        '''
        SELECT
            concept_local_name,
            value_numeric,
            unit,
            context_ref
        FROM financial_facts
        WHERE company_number = '10238359'
          ;
        ''',
        conn,
    )

df

,concept_local_name,value_numeric,unit,context_ref
0,AccruedLiabilitiesDeferredIncome,93988,GBP,B_B_M
1,AccruedLiabilitiesDeferredIncome,190393,GBP,E_B_M
2,AccumulatedDepreciationImpairmentPropertyPlant...,2557,GBP,A_Z_AB
3,AverageNumberEmployeesDuringPeriod,2,Pure,C
4,AverageNumberEmployeesDuringPeriod,2,Pure,F
5,CashBankOnHand,670600,GBP,B
6,CashBankOnHand,171815,GBP,E
7,CorporationTaxPayable,99433,GBP,B_B_M
8,CorporationTaxPayable,190196,GBP,E_B_M
9,Creditors,214372,GBP,B_B_M
10,Creditors,214372,GBP,B_B_M_F_N
11,Creditors,389665,GBP,E_B_M
12,Creditors,389665,GBP,E_B_M_F_N
13,CurrentAssets,933925,GBP,B
14,CurrentAssets,1051784,GBP,E
15,Debtors,263325,GBP,B
16,Debtors,263325,GBP,B_B_M_F_N
17,Debtors,879969,GBP,E
18,Debtors,879969,GBP,E_B_M_F_N
19,Equity,719753,GBP,B
20,Equity,75000,GBP,B_T_U
21,Equity,644753,GBP,B_T_V
22,Equity,662319,GBP,E
23,Equity,75000,GBP,E_T_U
24,Equity,587319,GBP,E_T_V
25,InvestmentsFixedAssets,200,GBP,B
26,InvestmentsFixedAssets,200,GBP,E
27,NetCurrentAssetsLiabilities,719553,GBP,B
28,NetCurrentAssetsLiabilities,662119,GBP,E
29,OtherCreditors,3,GBP,B_B_M
30,OtherCreditors,66,GBP,E_B_M
31,OtherDebtors,2960,GBP,B_B_M
32,OtherDebtors,443218,GBP,E_B_M
33,OtherInvestmentsOtherThanLoans,200,GBP,B
34,OtherInvestmentsOtherThanLoans,200,GBP,E
35,OtherTaxationSocialSecurityPayable,20948,GBP,B_B_M
36,OtherTaxationSocialSecurityPayable,9010,GBP,E_B_M
37,PrepaymentsAccruedIncome,3898,GBP,B_B_M
38,PrepaymentsAccruedIncome,5453,GBP,E_B_M
39,PropertyPlantEquipment,0,GBP,B_Z_AB
40,PropertyPlantEquipment,0,GBP,E_Z_AB
41,PropertyPlantEquipmentGrossCost,2557,GBP,A_Z_AB
42,TotalAssetsLessCurrentLiabilities,719753,GBP,B
43,TotalAssetsLessCurrentLiabilities,662319,GBP,E
44,TradeDebtorsTradeReceivables,256467,GBP,B_B_M
45,TradeDebtorsTradeReceivables,431298,GBP,E_B_M